rest_picker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rest_picker/',include('restaurants.urls',namespace='restaurants')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from restaurants.models import Food
from django.conf.urls import url
from django.views.generic import ListView
from django.conf.urls.static import static
from django.conf import settings
from restaurants import views

urlpatterns = [
    url(r'^$', ListView.as_view(model=Food,
                                template_name='restaurants/new.html')),
    url(r'^food/(?P<food_id>\d+)/$', views.choose_town, name='choose_town'),
    url(r'^food/(?P<food_id>\d+)/town/(?P<town_id>\d+)/$',
        views.choose_restaurant, name='choose_restaurant'),
    url(r'^rest/(?P<rest_id>\d+)/$', views.restaurant, name='restaurant'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

restaurants/models.py
from django.db import models

class Food(models.Model):
    name = models.CharField(max_length = 50);
    picture = models.ImageField(null = True);

    def __str__(self):
        return self.name;
    
class Type(models.Model):
    type = models.CharField(max_length = 30);

    def __str__(self):
        return self.type;
    
    
class Town(models.Model):
    name = models.CharField(max_length = 50);
    picture = models.ImageField(upload_to = 'images/', null = True, blank = True)
    def __str__(self):
        return self.name;
    
class Restaurant(models.Model):
    name = models.CharField(max_length = 30);
    phone = models.CharField(max_length = 12);
    address = models.CharField(max_length = 100);
    food = models.ForeignKey(Food);
    town = models.ForeignKey(Town);
    cost = models.CharField(max_length = 20);
    restaurant_type = models.ForeignKey(Type);
    menu = models.ImageField(upload_to = 'images/', null = True, blank = True );
    map = models.ImageField(upload_to = 'images/', null = True, blank = True);
    picture = models.ImageField(upload_to = 'images/', null = True, blank = True);

    STARS = ((1,'one'),(2,'two'),(3,'three'),(4,'four'),(5,'five'),);
    votes = models.IntegerField(choices = STARS, default = 4);

    def __str__(self):
        return self.name;
    

# Create your models here.

restaurants/views.py
from django.shortcuts import render
from restaurants.models import Food, Restaurant, Type, Town
from django.http import HttpResponse

def search(request):
    error = False
    if 'search' in request.GET:
        q = request.GET['search']
        if not q:
            error = True
        else:
            restaurants = Restaurants.ojects.filter(title__icontains=search)
            return render(request, 'choose_restaurant.html',{'rests' : restaurants, 'query':q})
    return render(request, 'new.html',{'error':error})

def choose_town(request, food_id):
    rest_list = Restaurant.objects.filter(food=food_id)
    town_list = []
    for r in rest_list:
        t = Town.objects.get(id = r.town.id)
        if t not in town_list:
            town_list.append(t)
    return render(request, 'restaurants/choose_town.html',{'food_id':food_id, 'town_list': town_list})

def choose_restaurant(request, food_id, town_id):
    rests = Restaurant.objects.filter(food__id = food_id, town__id = town_id)
    return render(request, 'restaurants/choose_restaurant.html',{'rests':rests})
        
def restaurant(request, rest_id):
    rest = Restaurant.objects.get(id = rest_id)
    return render(request, 'restaurants/restaurant.html',{'restaurant':rest})
            
    
# Create your views here.

restaurants/templates/restaurants/choose_restaurant.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <title>Choose Restaurant</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
	<link href = "{% static 'css/style.css' %}" rel="stylesheet">
	
    <!-- Custom CSS -->
    <link href="{% static 'csspage2/1-col-portfolio.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<div id="header">
			<div id="logo-wrapper">
				<div style="container">
						
					<!-- Logo -->
						<div id="logo">
							<p><a href="#">Let's Eat!</a></p>
						</div>
					
				</div>
			</div>
	</div>

    <!-- Page Content -->
    <div class="container">
		<div class = "main">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Choose Restaurant
                </h1>
            </div>
        </div>
        <!-- /.row -->
		{% if rests %}
        <!-- Project One -->
		{% for r in rests %}
        <div class="row">
            <div class="col-md-7">
                    <img class="img-responsive" src="{{r.picture}}" alt="">
            </div>
            <div class="col-md-5">
                <h3>{{ r.name }}</h3><br>
                <a class="btn btn-primary" href="{% url 'restaurants:restaurant' r.id %}"">Let's Go!<span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        {% endfor %}
		{% endif %}
    </div>
</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

restaurants/templates/restaurants/choose_town.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <title>Choose Town</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
	<link href = "{% static 'css/style.css' %}" rel="stylesheet">
	
    <!-- Custom CSS -->
    <link href="{% static 'csspage2/1-col-portfolio.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<div id="header">
			<div id="logo-wrapper">
				<div style="container">
						
					<!-- Logo -->
						<div id="logo">
							<p><a href="#">Let's Eat!</a></p>
						</div>
					
				</div>
			</div>
	</div>

    <!-- Page Content -->
    <div class="container">
		<div class = "main">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Choose Town
                </h1>
            </div>
        </div>
        <!-- /.row -->
		{% if town_list %}
        <!-- Project One -->
		{% for town_dict in town_list %}
        <div class="row">
            <div class="col-md-7">
                    <img class="img-responsive" src="{{ town_dict.picture.url }}" alt="">
            </div>
            <div class="col-md-5">
                <h3>{{ town_dict.name }}</h3><br>
                <a class="btn btn-primary" href="{% url 'restaurants:choose_restaurant' food_id town_dict.id %}">Let's Go!<span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        {% endfor %}
		{% endif %}
    </div>
</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

restaurants/templates/restaurants/index.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
	<head>
		<title>Restaurant picker</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="shortcut icon" href="favicon.ico">
		<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
		<link rel="icon" href="data:;base64,iVBORw0KGgo=">
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
		<script src="{% static 'js/skel.min.js' %}"></script>
		<script src="{% static 'js/skel-panels.min.js' %}"></script>
		<script src="{% static 'js/init.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/skel-noscript.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style-desktop.css' %}" />
	</head>
	<body class="homepage">

	<!-- Header -->
		<div id="header">
			<div id="logo-wrapper">
				<div class="container">
						
					<!-- Logo -->
						<div id="logo">
							<h1>Let's Eat!</h1>
						</div>
					
				</div>
			</div>
		</div>
			
	<!-- Header -->
		
	<!-- Banner -->
		<div id="banner1">
			<img src = "{% static 'images/pizza-stock.jpg' %}" id = "pizza"/>
			<input type = "text" name = "search" placeholder = "Search" id = "search">
			<br><br><br><br><br>
		</div>
	<!-- /Banner -->

	<!-- Main -->
		<div id="main">
		<p align="center" class="intro" >What do you want to eat today?</p>
			<!-- Featured -->
			<div class="container">
			{% if food_list %}
				
			<div class="row">
				{% for f in food_list %}
					<div class="row">
						<div class="col-md-7">
							<a href = "{% url 'restaurants:choose_town' f.id %}">
							<img class="img-responsive" src="{{ f.picture.url }}" alt=""></a>
						</div>
						<div class="col-md-5">
							<h1>{{ f.name }}</h1><br>
						</div>
					</div>
				{% endfor %}
					</div>
			{% endif %}
			<!-- /Featured -->
			
			</div>
			<!-- /Main Content -->
			
		</div>
	<!-- /Main -->
	<!-- Copyright -->
		<div id="copyright">
			<div class="container">
				<section>
				</section>
			</div>
		</div>

	</body>
</html>

restaurants/templates/restaurants/index1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <title>Choose Town</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="{% static 'js/skel.min.js' %}"></script>
	<script src="{% static 'js/skel-panels.min.js' %}"></script>
	<script src="{% static 'js/init.js' %}"></script>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
	<link href = "{% static 'css/style.css' %}" rel="stylesheet">
	
    <!-- Custom CSS -->
    <link href="{% static 'csspage2/1-col-portfolio.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class = "homepage">

	<div id="header">
			<div id="logo-wrapper">
				<div style="container">
						
					<!-- Logo -->
						<div id="logo">
							<p><a href="#">Let's Eat!</a></p>
						</div>
					
				</div>
			</div>
	</div>
	
	<div id="banner1">
			<img src = "{% static 'images/pizza-stock.jpg' %}" id = "pizza"/>
			<input type = "text" name = "search" placeholder = "Search" id = "search">
			<br><br><br><br><br>
	</div>
		
    <!-- Page Content -->
    <div class="container">
		<div class = "main">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">What would you like to eat today?
                </h1>
            </div>
        </div>
		</div>
		</div>
        <!-- /.row -->
		{% if food_list %}
		<div class = "row">
        <!-- Project One -->
		{% for f in town_list %}
        <div class="row">
            <div class="col-md-7">
                    <a href = "#"><img class="img-responsive" src= "{{f.picture.url}}" alt=""></a>
            </div>
            <div class="col-md-5">
                <h3>{{f.name}}</h3><br>
            </div>
        </div>
        <!-- /.row -->
        <hr>
        {% endfor %}
		</div>
		{% endif %}
    
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

restaurants/templates/restaurants/new.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <title>Choose Town</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
	<link href = "{% static 'css/style.css' %}" rel="stylesheet">
	
    <!-- Custom CSS -->
    <link href="{% static 'csspage2/1-col-portfolio.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<div id="header" class="header col-xs-12 col-sm-12 ">
			<div id="logo-wrapper">
				<div style="container">
						
					<!-- Logo -->
						<div id="logo">
							<p><a href="#">Let's Eat!</a></p>
						</div>
					
				</div>
			</div>
	</div>

    <!-- Page Content -->
        <!-- Page Heading -->
			<div id="banner1">
				<img src = "{% static 'images/pizza-stock.jpg' %}" id = "pizza" style="max-width:100%;" />
				<br><br>
				<form action = "/choose_restaurant/" method = "get">
				<div class = "row" style="width:1000px; margin:0 auto; background:#333">
				<div class = "col-md-9" style = "background:#333">
				<input type = "text" name = "search" placeholder = 	"Search" id = "search"></div>
				<div class = "col-md-3" style = "background:#333">
				<input type = "button" class = "button" name = "GO!"></input></div></form>
				</div><br>
				{% if error %}
				<p>Please enter a valid search term</p>
				{% endif %}
				<br>
            </div>
			<p align="center" class="intro" >What do you want to eat today?</p><br>
			<!-- Featured -->
			<div class="container">
			{% if food_list %}
				
			<div class="row">
				{% for f in food_list %}
					<div class="row" style="width:800px; margin:0 auto;">
						<div class="col-md-8">
							<a href = "{% url 'restaurants:choose_town' f.id %}">
							<img class="img-responsive" src="{{ f.picture.url }}" alt="" style="width:400px;height:228px;"></a>
							<br><br>
						</div>
						<div class="col-md-4">
							<h1>{{ f.name }}</h1><br>
						</div>
					</div>
				{% endfor %}
					</div>
			{% endif %}
			<!-- /Featured -->
			
			</div>

    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

restaurants/templates/restaurants/restaurant.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <title>Restaurant</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'csspage2/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel = "stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'csspage2/portfolio-item.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
	<div id="header">
			<div id="logo-wrapper">
				<div style="container">
						
					<!-- Logo -->
						<div id="logo">
							<p><a href="#">Let's Eat!</a></p>
						</div>
					
				</div>
			</div>
	</div>
    <!-- Navigation -->
    

    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{restaurant.name}}
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                <img class="img-responsive" src="{{restaurant.picture}}" alt="">
            </div>

            <div class="col-md-4">
				<h3>Restaurant Type : {{restaurant.restaurant_type}}</h3>
                <h3>Phone : {{restaurant.phone}}</h3>
                <h3>Address: {{restaurant.address}}</h3>
                <h3>Cost for two: {{restaurant.cost}}</h3>
                
            </div>

        </div>
        <hr>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>